### Numpy

In [3]:
import numpy as np

In [5]:
my_list = [ 1, 2, 3, 4, 5 ]
print(type(my_list))
np.array(my_list)

<class 'list'>


array([1, 2, 3, 4, 5])

In [106]:
np.arange(5)
len(np.arange(5))
np.linspace(1,10,10)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [157]:
np.zeros((3,3))
np.ones((3,3)) * np.random.randint(10)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [159]:
np.zeros((2,2)).tolist()

[[0.0, 0.0], [0.0, 0.0]]

In [156]:
np.random.rand(2,2) # uniform distribution

array([[0.64720858, 0.27356659],
       [0.48225618, 0.58054085]])

In [190]:
np.random.randint(10, size = (3, 3))

array([[1, 7, 5],
       [8, 4, 7],
       [6, 6, 2]])