<a href='https://numpy.org/doc/stable/index.html'><img src='numpy_logo.png'/></a>

In [3]:
import numpy as np

<font size= '5px' color='blue'>Python list to numpy array and vice versa</font>

In [1]:
# Normal python list
my_list = [ 1, 2, 3, 4, 5 ]
type(my_list)

list

In [4]:
array = np.array(my_list)
type(array)

numpy.ndarray

In [10]:
array.tolist()

28

<font size= '5px' color='blue'>Two dimensional arrays</font>


In [21]:
shape = (3,3) # rows, columns
zeros_array = np.zeros(shape)
print(zeros_array.shape)
zeros_array.dtype

# Encouraged to examine the output of zeros array


(3, 3)


dtype('float64')

In [31]:
two_dimensional = np.full((3,3), fill_value = 7)

#two_dimensional += 2

# Examine sevens 2D array


<font size= '5px' color='blue'>Random numbers</font>

In [132]:
rng = np.random.default_rng(seed = 42)
# uniform distribution
rng.random((3,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [123]:
rng.integers(10, size =6)

array([8, 4, 5, 3, 1, 9])

In [124]:
rng.integers(10, size = (3, 3))

array([[7, 6, 4],
       [8, 5, 4],
       [4, 2, 0]])

<font size= '5px' color='blue'>Evenly spaced values</font>

In [135]:
arange_array = np.arange(5)
# Check the length
len(arange_array)

#array[array % 2 == 0]

array([0, 2, 4])

In [125]:
a = np.arange(9).reshape(3,3)
top_corner = a[:2,:2]
top_corner += 1
a

[0 2 4 6 8]


array([[1, 2, 2],
       [4, 5, 5],
       [6, 7, 8]])

<a href='https://pandas.pydata.org/docs/'><img src='pandas_logo.png'/></a>

In [138]:
import pandas as pd

<font size= '5px' color='blue'>Creating a dataframe from a dictionary</font>

In [172]:
dictionary = {
    'a':[1,2,3],
    'b':[4,5,6],
    'c':[7,8,9]
}
df = pd.DataFrame(dictionary)

#pd.DataFrame(data = dictionary.values(), index = range(3), columns = dictionary.keys())
#df.to_numpy()

In [173]:
df.iloc[0]

a    1
b    4
c    7
Name: 0, dtype: int64

In [174]:
df = pd.read_csv('times_tables.csv', index_col = 0)
df

x 1  x 2  x 3  x 4  x 5  x 6  x 7  x 8  x 9  x 10
Row 1     1    2    3    4    5    6    7    8    9    10
Row 2     2    4    6    8   10   12   14   16   18    20
Row 3     3    6    9   12   15   18   21   24   27    30
Row 4     4    8   12   16   20   24   28   32   36    40
Row 5     5   10   15   20   25   30   35   40   45    50
Row 6     6   12   18   24   30   36   42   48   54    60
Row 7     7   14   21   28   35   42   49   56   63    70
Row 8     8   16   24   32   40   48   56   64   72    80
Row 9     9   18   27   36   45   54   63   72   81    90
Row 10   10   20   30   40   50   60   70   80   90   100

In [ ]:
df.head()

#df.tail()
#df.sample(3)

In [162]:
df.info()
#df.columns # returns a base index object for columns
#df.index # returns a base index object for the rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
dtypes: int64(3)
memory usage: 200.0 bytes


RangeIndex(start=0, stop=3, step=1)

In [155]:
df.describe().T

count  mean        std   min    25%   50%    75%    max
x 1    10.0   5.5   3.027650   1.0   3.25   5.5   7.75   10.0
x 2    10.0  11.0   6.055301   2.0   6.50  11.0  15.50   20.0
x 3    10.0  16.5   9.082951   3.0   9.75  16.5  23.25   30.0
x 4    10.0  22.0  12.110601   4.0  13.00  22.0  31.00   40.0
x 5    10.0  27.5  15.138252   5.0  16.25  27.5  38.75   50.0
x 6    10.0  33.0  18.165902   6.0  19.50  33.0  46.50   60.0
x 7    10.0  38.5  21.193552   7.0  22.75  38.5  54.25   70.0
x 8    10.0  44.0  24.221203   8.0  26.00  44.0  62.00   80.0
x 9    10.0  49.5  27.248853   9.0  29.25  49.5  69.75   90.0
x 10   10.0  55.0  30.276504  10.0  32.50  55.0  77.50  100.0

In [159]:
series_7 = df.loc['Row 7']
#series_7['x 6']

<font size= '5px' color='blue'>Adding a column/row</font>

In [177]:
df

x 1  x 2  x 3  x 4  x 5  x 6  x 7  x 8  x 9  x 10
Row 1     1    2    3    4    5    6    7    8    9    10
Row 2     2    4    6    8   10   12   14   16   18    20
Row 3     3    6    9   12   15   18   21   24   27    30
Row 4     4    8   12   16   20   24   28   32   36    40
Row 5     5   10   15   20   25   30   35   40   45    50
Row 6     6   12   18   24   30   36   42   48   54    60
Row 7     7   14   21   28   35   42   49   56   63    70
Row 8     8   16   24   32   40   48   56   64   72    80
Row 9     9   18   27   36   45   54   63   72   81    90
Row 10   10   20   30   40   50   60   70   80   90   100
Row 11   11   22   33   44   55   66   77   88   99   110

In [176]:
df.loc['Row 11'] = [x * 11 for x in range(1,11)]
df

x 1  x 2  x 3  x 4  x 5  x 6  x 7  x 8  x 9  x 10
Row 1     1    2    3    4    5    6    7    8    9    10
Row 2     2    4    6    8   10   12   14   16   18    20
Row 3     3    6    9   12   15   18   21   24   27    30
Row 4     4    8   12   16   20   24   28   32   36    40
Row 5     5   10   15   20   25   30   35   40   45    50
Row 6     6   12   18   24   30   36   42   48   54    60
Row 7     7   14   21   28   35   42   49   56   63    70
Row 8     8   16   24   32   40   48   56   64   72    80
Row 9     9   18   27   36   45   54   63   72   81    90
Row 10   10   20   30   40   50   60   70   80   90   100
Row 11   11   22   33   44   55   66   77   88   99   110

In [178]:
df.loc[:, 'x 11'] = [x * 11 for x in range(1,12)]
df

x 1  x 2  x 3  x 4  x 5  x 6  x 7  x 8  x 9  x 10  x 11
Row 1     1    2    3    4    5    6    7    8    9    10    11
Row 2     2    4    6    8   10   12   14   16   18    20    22
Row 3     3    6    9   12   15   18   21   24   27    30    33
Row 4     4    8   12   16   20   24   28   32   36    40    44
Row 5     5   10   15   20   25   30   35   40   45    50    55
Row 6     6   12   18   24   30   36   42   48   54    60    66
Row 7     7   14   21   28   35   42   49   56   63    70    77
Row 8     8   16   24   32   40   48   56   64   72    80    88
Row 9     9   18   27   36   45   54   63   72   81    90    99
Row 10   10   20   30   40   50   60   70   80   90   100   110
Row 11   11   22   33   44   55   66   77   88   99   110   121