### Numpy

In [206]:
!{sys.executable} -m pip show numpy

Name: numpy
Version: 1.23.4
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: /Users/amun/Documents/computer/syntax_testing/python/ipython_venv_3.10.4/lib/python3.10/site-packages
Requires: 
Required-by: Backtesting, bokeh, contourpy, matplotlib, pandas


In [2]:
import numpy as np

In [56]:
my_list = [ 1, 2, 3, 4, 5 ]
print(type(my_list))
array = np.array(my_list)
print(type(array))
array.tolist()


<class 'list'>
<class 'numpy.ndarray'>


[1, 2, 3, 4, 5]

In [60]:
np.arange(5)
len(np.arange(5))


5

In [157]:
np.zeros((3,3))
np.ones((3,3)) * np.random.randint(10)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [156]:
np.random.rand(2,2) # uniform distribution

array([[0.64720858, 0.27356659],
       [0.48225618, 0.58054085]])

In [54]:
np.random.randint(10, size = (3, 3))

array([[3, 5, 2],
       [7, 2, 9],
       [6, 6, 8]])

In [63]:
np.random.seed(0)
np.random.randint(10, size =6)

array([5, 0, 3, 3, 7, 9])

In [40]:
a = np.arange(9).reshape(3,3)
print(a[a % 2 == 0])
top_corner = a[:2,:2]
top_corner += 1
a

[0 2 4 6 8]


array([[1, 2, 2],
       [4, 5, 5],
       [6, 7, 8]])

In [114]:
import pandas as pd
np.random.seed(42)
dr = pd.date_range('20000101', periods = 5) # create datetime index
df = pd.DataFrame(np.random.randint(10, size=(5,5)), index = dr, columns = list('abcde'))
print(df)
df.sort_index(axis =1, ascending = False)
df.describe().T

            a  b  c  d  e
2000-01-01  6  3  7  4  6
2000-01-02  9  2  6  7  4
2000-01-03  3  7  7  2  5
2000-01-04  4  1  7  5  1
2000-01-05  4  0  9  5  8


count  mean       std  min  25%  50%  75%  max
a    5.0   5.2  2.387467  3.0  4.0  4.0  6.0  9.0
b    5.0   2.6  2.701851  0.0  1.0  2.0  3.0  7.0
c    5.0   7.2  1.095445  6.0  7.0  7.0  7.0  9.0
d    5.0   4.6  1.816590  2.0  4.0  5.0  5.0  7.0
e    5.0   4.8  2.588436  1.0  4.0  5.0  6.0  8.0

In [204]:
# values = [np.linspace(1 * i,10 * i,10, dtype = np.int32) for i in range(1,11)]
# column_headers = [f'x {n}' for n in range(1,11)]
# indexes = [f'Row {n}' for n in range(1,11)]
# df = pd.DataFrame(data = values, index = indexes, columns = column_headers)
# df.describe().T
df = pd.read_csv('times_tables.csv', index_col = 0)
df.head()
df.tail()
series_1_locate = df.loc['Row 1']
series_7 = df.iloc[6]
df.describe().T
series_7['x 6']
# df.info()
df.sample(3)
df.columns # returns a base index object for columns
df.index # returns a base index object for the rows
df.loc['Row 11'] = [x * 11 for x in range(1,11)]
df.loc['Row 12'] = [x * 12 for x in range(1,11)]
df.loc[:, 'x 11'] = [x * 11 for x in range(1,13)]
df.to_numpy()
# df

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132]])